#!/usr/bin/env bash
# Create ~/.claude/obsidian-sync.env from cursor-sync/.env if missing.
set -euo pipefail

TARGET="$HOME/.claude/obsidian-sync.env"
SOURCE="$HOME/.claude/cursor-sync/.env"

if [[ -f "$TARGET" ]]; then
  echo "obsidian-sync.env already exists: $TARGET"
  exit 0
fi

if [[ ! -f "$SOURCE" ]]; then
  echo "Missing $SOURCE — create it with NOTION_TOKEN=..." >&2
  exit 1
fi

mkdir -p "$(dirname "$TARGET")"
{
  echo "# Generated by company-hq/tools/knowledge_sync/setup-obsidian-env.sh"
  echo "# Copy additional keys from scripts/obsidian-sync.env.example as needed."
  grep -E '^(NOTION_TOKEN|NOTION_DAILY_DB_ID)=' "$SOURCE" || true
} > "$TARGET"

if ! grep -q '^NOTION_TOKEN=' "$TARGET"; then
  echo "NOTION_TOKEN not found in $SOURCE" >&2
  rm -f "$TARGET"
  exit 1
fi

chmod 600 "$TARGET"
echo "Created $TARGET"
